### ISSUE TITLE
you stole those games from 3kh0

### ISSUE THREAD

**Issue by coolestniceguy21** [Animationking11/unblockedgames#1]
smh... please remove them
you know what i'm talking about

**Comment by OddPvP** [comment]
Its an open source project and I didn't steal most of the games directly I got a lot from other repos also all unblocked games sites steal from each other I just compiled them all and made the UI If people stole from my repo I wouldn't care even if they stole the main site UI that I custom coded that's the point of open-source.

**Comment by OddPvP** [comment]
So yes I did. 3kh0 has reached out to us directly on our main repo and although I am sure he is not the happiest about me using his repo. I think he understands where I am coming from.
