### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by 3kh0** [Animationking11/unblockedgames#4]
Hello there!

I have looked through your GitHub repo and I found some things that I believe were taken from my site. I ask that you take them down to respect my work and what I do.
If the original one was blocked then you can contact me and I can give you more links. If you have any questions please feel free to reach out to me!

Thanks!
Echo

**Comment by Animationking11** [comment]
Sure! If you could give me a list of the games you made I can remove them

**Comment by Animationking11** [comment]
You did not make BloonsTD or Ducklife, Just because the games are on your site does not mean you created them. I didn't just use your repo to find them I used multiple so no I don't remember where I got all the games from.

**Comment by Animationking11** [comment]
Also I took cupcakes from the official repo not yours. https://github.com/0x0800/2048-CUPCAKES

**Comment by 3kh0** [comment]
Your games have my tracking beacon

**Comment by 3kh0** [comment]
That is how I found you

**Comment by Animationking11** [comment]
Even if it does all that means is you added a few lines of code

**Comment by coolestniceguy21** [comment]
very unprofessional of you

**Comment by 3kh0** [comment]
Yeah but you took it from me, and I do not allow that, so please respect my work and remove it.

**Comment by Animationking11** [comment]
Why is it open source then?

**Comment by 3kh0** [comment]
For people to improve on, not just take like a skid. Did you even take the time to read the LICENCE file?

**Comment by Animationking11** [comment]
I won't take down games unless you were the creator, Sorry but I will not be taking them down.
