### ISSUE TITLE
just a quick question

### ISSUE THREAD

**Issue by InfernoCoding** [Animationking11/unblockedgames#6]
its fine if you dont want to answer but, how do you duplicate the game to put on your page?
ive tried using save as but it just doesnt work 
tysm

**Comment by InfernoCoding** [comment]
oh yeah btw i give your project a star this is like the best site ever lol :)

**Comment by Animationking11** [comment]
Thanks for the star, but yeah I can't tell you how I get each game. But if you want me to add any games to my site you can put a recommendation in our discord server https://discord.gg/xksWyP9aJv.
